"""add product soft-delete fields

Revision ID: 1f740fff8426
Revises: f9d6467f0819
Create Date: 2026-07-31 18:16:53.633010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f740fff8426'
down_revision: Union[str, None] = 'f9d6467f0819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('archived_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['archived_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'archived_by_id')
    op.drop_column('products', 'archived_at')
    # ### end Alembic commands ###
